title: Kevin Amerson
email: kevin.amerson@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Technology enthusiast, Entrepreneur, Investor, Software Engineer, Mechanical Engineer

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kevinamerson.com" # the base hostname & protocol for your site

highlighter: pygments

twitter_user: https://twitter.com/kevinamerson
github_user: https://github.com/caoimhghin

markdown: kramdown
permalink: pretty
